name: build and deploy workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build-Deploy:
    runs-on: ubuntu-18.04    
    steps:
      - name: 'Set up Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: 'npm run docs:build'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist
